sonar.projectKey=eatinity
sonar.projectName=Eatinity Secure E-Commerce Platform
sonar.sourceEncoding=UTF-8
sonar.sources=eatinity-frontend/src,eatinity-prod/lambda,eatinity-iac
sonar.tests=eatinity-prod/tests
sonar.test.inclusions=eatinity-prod/tests/**/*.py
sonar.exclusions=**/node_modules/**,**/dist/**,**/__pycache__/**,**/*.zip,**/*.tfstate*,**/*.tfplan,**/stripe_package/**
sonar.python.version=3.12

